"""Añadir doc individual del jefe a vacation_periods

Revision ID: 00c2a3a0d6c0
Revises: 'aaa717af6d1c'
Create Date: 2025-11-17 15:17:32.435068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c2a3a0d6c0'
down_revision = 'aaa717af6d1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###