"""Add modification_requests table

Revision ID: 167c3d33dedc
Revises: '4dd03cf9be66'
Create Date: 2025-11-14 20:59:16.767430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167c3d33dedc'
down_revision = '4dd03cf9be66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###