"""Add suspension_requests table

Revision ID: 18e966316176
Revises: '31c8c3b41d12'
Create Date: 2025-11-14 22:00:55.762843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e966316176'
down_revision = '31c8c3b41d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###