"""Add proposed_changes_to_modification_requests

Revision ID: 1ec2977c1b18
Revises: '61c9c0ceecbb'
Create Date: 2025-11-14 21:47:29.602304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec2977c1b18'
down_revision = '61c9c0ceecbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modification_requests', sa.Column('new_start_date', sa.Date(), nullable=True))
    op.add_column('modification_requests', sa.Column('new_period_type', sa.Integer(), nullable=True))
    op.add_column('modification_requests', sa.Column('new_end_date', sa.Date(), nullable=True))
    op.add_column('modification_requests', sa.Column('new_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modification_requests', 'new_days')
    op.drop_column('modification_requests', 'new_end_date')
    op.drop_column('modification_requests', 'new_period_type')
    op.drop_column('modification_requests', 'new_start_date')
    # ### end Alembic commands ###