"""add location to holidays and users

Revision ID: 23c2b1040766
Revises: '636f0ea0caf2'
Create Date: 2025-11-19 17:02:42.257043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c2b1040766'
down_revision = '636f0ea0caf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('location', sa.String(length=50), nullable=True))
    op.drop_index(op.f('holiday_date'), table_name='holidays')
    op.add_column('users', sa.Column('location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.create_index(op.f('holiday_date'), 'holidays', ['holiday_date'], unique=True)
    op.drop_column('holidays', 'location')
    # ### end Alembic commands ###