"""Add vacation_log table

Revision ID: 31c8c3b41d12
Revises: '3fd69b296590'
Create Date: 2025-11-14 21:57:32.283533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c8c3b41d12'
down_revision = '3fd69b296590'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_period_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacation_period_id'], ['vacation_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_logs_id'), 'vacation_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_logs_id'), table_name='vacation_logs')
    op.drop_table('vacation_logs')
    # ### end Alembic commands ###