"""Añadir vacation_days_total y manager_id a User

Revision ID: 3770e47796a4
Revises: '6db865a9af2b'
Create Date: 2025-11-17 15:55:41.994778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3770e47796a4'
down_revision = '6db865a9af2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vacation_days_total', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'manager_id')
    op.drop_column('users', 'vacation_days_total')
    # ### end Alembic commands ###