"""Add vacation_log table

Revision ID: 3fd69b296590
Revises: '1ec2977c1b18'
Create Date: 2025-11-14 21:52:44.948631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd69b296590'
down_revision = '1ec2977c1b18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###