"""Añadir doc individual del jefe a vacation_periods

Revision ID: 475e7c690efc
Revises: '00c2a3a0d6c0'
Create Date: 2025-11-17 15:18:45.259472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475e7c690efc'
down_revision = '00c2a3a0d6c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_periods', sa.Column('manager_individual_doc_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_periods', 'manager_individual_doc_path')
    # ### end Alembic commands ###