"""Add consolidated_doc_path to vacation_period

Revision ID: 4dd03cf9be66
Revises: '7c3c8250467e'
Create Date: 2025-11-14 20:56:54.505735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd03cf9be66'
down_revision = '7c3c8250467e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation_periods', sa.Column('consolidated_doc_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacation_periods', 'consolidated_doc_path')
    # ### end Alembic commands ###