"""Add proposed_changes_to_modification_requests

Revision ID: 61c9c0ceecbb
Revises: '99ea91be9208'
Create Date: 2025-11-14 21:37:41.965777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c9c0ceecbb'
down_revision = '99ea91be9208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###