"""add vacation policies

Revision ID: 636f0ea0caf2
Revises: '450035209427'
Create Date: 2025-11-19 14:33:53.825150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636f0ea0caf2'
down_revision = '450035209427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allowed_months', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vacation_policies_id'), 'vacation_policies', ['id'], unique=False)
    op.add_column('users', sa.Column('vacation_policy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'vacation_policies', ['vacation_policy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'vacation_policy_id')
    op.drop_index(op.f('ix_vacation_policies_id'), table_name='vacation_policies')
    op.drop_table('vacation_policies')
    # ### end Alembic commands ###