"""add can_request_own_vacation flag

Revision ID: 6b56716a0d2b
Revises: '23c2b1040766'
Create Date: 2025-12-04 20:27:53.144996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b56716a0d2b'
down_revision = '23c2b1040766'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_request_own_vacation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_request_own_vacation')
    # ### end Alembic commands ###