"""Añadir force_password_change a User

Revision ID: 6db865a9af2b
Revises: '475e7c690efc'
Create Date: 2025-11-17 15:36:11.058862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db865a9af2b'
down_revision = '475e7c690efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('force_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_password_change')
    # ### end Alembic commands ###