"""Add consolidated_doc_path to vacation_period

Revision ID: 7c3c8250467e
Revises: 'a0ed99d396c8'
Create Date: 2025-11-14 20:52:05.602157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3c8250467e'
down_revision = 'a0ed99d396c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###