"""Add modification_requests table

Revision ID: 99ea91be9208
Revises: '167c3d33dedc'
Create Date: 2025-11-14 21:11:50.573405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ea91be9208'
down_revision = '167c3d33dedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modification_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_period_id', sa.Integer(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('attached_doc_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacation_period_id'], ['vacation_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modification_requests_id'), 'modification_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modification_requests_id'), table_name='modification_requests')
    op.drop_table('modification_requests')
    # ### end Alembic commands ###