"""Add vacation_log table

Revision ID: aaa717af6d1c
Revises: '18e966316176'
Create Date: 2025-11-14 22:04:55.715525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa717af6d1c'
down_revision = '18e966316176'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspension_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacation_period_id', sa.Integer(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=True),
    sa.Column('suspension_type', sa.String(length=20), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('attached_doc_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('new_end_date_parcial', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vacation_period_id'], ['vacation_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspension_requests_id'), 'suspension_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspension_requests_id'), table_name='suspension_requests')
    op.drop_table('suspension_requests')
    # ### end Alembic commands ###